### PR TITLE
fix: adjust comments to mention apps instead of extensions

### PR DESCRIPTION
**Pull request by andipaetzold**
# Purpose of PR

We call the library App SDK and apps are the latest way to extend Contentful. We should therefore also not refer to legacy extensions in our comments.

### CODE REVIEW

**Review by kdamball — APPROVED** [review]
Always wanted this change to happen but was told no before 😅 . Happy to see it finally

**Comment by loweisz** [comment]
Lgtm, I'm just wondering if we maybe could say both, "app or extension" like it was done [here](https://github.com/contentful/ui-extensions-sdk/pull/880/files#diff-ae76f63dff4e8844cc9a810b9cc63e79a33fdeecb5630ad60a50ea56c8f4b297R48)

**Comment by andipaetzold** [comment]
> Lgtm, I'm just wondering if we maybe could say both, "app or extension" like it was done [here](https://github.com/contentful/ui-extensions-sdk/pull/880/files#diff-ae76f63dff4e8844cc9a810b9cc63e79a33fdeecb5630ad60a50ea56c8f4b297R48)

I'd personally wouldn't do that.
The reason why we mention both here is that `openCurrent` has a specific implementation to handle both cases. On the same API there is `openExtension` and `openCurrentApp` that only handle one case.

We renamed everything in the repo to match refert to apps (including the name). So, I think this should be fine.

**Comment by loweisz** [comment]
Fair enough 👍

**Review by loweisz — APPROVED** [review]

**Review by fabe — APPROVED** [review]

**Pull request merged**
