### PR TITLE
fix: improve space API typings 

### PR DESCRIPTION
**Pull request by shikaan**
# Purpose of PR

Make SpaceAPI typings reflect reality being less ambiguous. This includes a non trivial refactoring of typings.

## Caveats

* Readme should explain reasoning behind current file structure. Happy to discuss that

### CODE REVIEW

**Comment by Jwhiles** [comment]
It would have been nice if the type changes and the file restructuring were separate commits, as it's quite hard to see what's different.

**Comment by shikaan** [comment]
> It would have been nice if the type changes and the file restructuring were separate commits, as it's quite hard to see what's different.

@Jwhiles You are right, I am sorry. I have started refactoring while I was midway through with SpaceAPI.

Here's a manually generated diff, should it help

```diff
@@ -1,47 +1,50 @@
 export interface SpaceAPI {
   getCachedContentTypes: () => ContentType[]
-  getContentType: <T = Object>(id: string) => Promise<T>
-  getContentTypes: <T = Object>() => Promise<CollectionResponse<T>>
-  createContentType: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  updateContentType: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  deleteContentType: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  deleteContentType: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
+  getContentType: (id: string) => Promise<ContentType>
+  getContentTypes: () => Promise<CollectionResponse<ContentType>>
+  createContentType: (data: WithOptionalSys<ContentType>) => Promise<ContentType>
+  updateContentType: (data: ContentType) => Promise<ContentType>
+  deleteContentType: (data: ContentType) => Promise<void>

-  getEntry: <T = Object>(id: string) => Promise<T>
-  getEntrySnapshots: <T = Object>(id: string) => Promise<CollectionResponse<T>>
-  getEntries: <T = Object, InputArgs = SearchQuery>(
-    query?: InputArgs
-  ) => Promise<CollectionResponse<T>>
-  createEntry: <T = Object, InputArgs = any>(contentTypeId: string, data: InputArgs) => Promise<T>
-  updateEntry: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  publishEntry: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  unpublishEntry: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  archiveEntry: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  unarchiveEntry: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  deleteEntry: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  getPublishedEntries: <T = Object, InputArgs = SearchQuery>(
-    query?: InputArgs
-  ) => Promise<CollectionResponse<T>>
+  getEntry: <Fields>(id: string) => Promise<Entry<Fields>>
+  getEntrySnapshots: <Fields>(id: string) => Promise<CollectionResponse<Snapshot<Entry<Fields>>>>
+  getEntries: <Fields, Query extends SearchQuery = SearchQuery>(
+    query?: Query
+  ) => Promise<CollectionResponse<Entry<Fields>>>
+  createEntry: <Fields>(
+    contentTypeId: string,
+    data: WithOptionalSys<Entry<Fields>>
+  ) => Promise<Entry<Fields>>
+  updateEntry: <Fields>(data: Entry<Fields>) => Promise<Entry<Fields>>
+  updateEntry: <Fields>(data: Entry<Fields>) => Promise<Entry<Fields>>
+  publishEntry: <Fields>(data: Entry<Fields>) => Promise<Entry<Fields>>
+  unpublishEntry: <Fields>(data: Entry<Fields>) => Promise<Entry<Fields>>
+  archiveEntry: <Fields>(data: Entry<Fields>) => Promise<Entry<Fields>>
+  unarchiveEntry: <Fields>(data: Entry<Fields>) => Promise<Entry<Fields>>
+  deleteEntry: <Fields>(data: Entry<Fields>) => Promise<void>
+  getPublishedEntries: <Fields, Query extends SearchQuery = SearchQuery>(
+    query?: Query
+  ) => Promise<CollectionResponse<Entry<Fields>>>

-  getAsset: <T = Object>(id: string) => Promise<T>
-  getAssets: <T = Object, InputArgs = SearchQuery>(
-    query?: InputArgs
-  ) => Promise<CollectionResponse<T>>
-  createAsset: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  updateAsset: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  deleteAsset: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  publishAsset: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  unpublishAsset: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  archiveAsset: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  processAsset: <T = Object, InputArgs = any>(data: InputArgs, locale: string) => Promise<T>
-  unarchiveAsset: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>
-  getPublishedAssets: <T = Object, InputArgs = SearchQuery>(
-    query?: InputArgs
-  ) => Promise<CollectionResponse<T>>
-  createUpload: (base64data: string) => void
+  getAsset: (id: string) => Promise<Asset>
+  getAssets: <Query extends SearchQuery = SearchQuery>(
+    query?: Query
+  ) => Promise<CollectionResponse<Asset>>
+  createAsset: (data: WithOptionalSys<Asset>) => Promise<Asset>
+  updateAsset: (data: Asset) => Promise<Asset>
+  deleteAsset: (data: Asset) => Promise<void>
+  publishAsset: (data: Asset) => Promise<Asset>
+  unpublishAsset: (data: Asset) => Promise<Asset>
+  archiveAsset: (data: Asset) => Promise<Asset>
+  processAsset: (data: Asset, locale: string) => Promise<Asset>
+  unarchiveAsset: (data: Asset) => Promise<Asset>
+  getPublishedAssets: <Query extends SearchQuery = SearchQuery>(
+    query?: Query
+  ) => Promise<CollectionResponse<Asset>>
+  createUpload: (base64data: string) => Promise<void>
   waitUntilAssetProcessed: (assetId: string, locale: string) => Promise<void>

   /** Returns all users who belong to the space. */
-  getUsers: <T = Object>() => Promise<CollectionResponse<T>>
+  getUsers: () => Promise<CollectionResponse<User>>

   /** Returns editor interface for a given content type */
   getEditorInterface: (contentTypeId: string) => Promise<EditorInterface>
@@ -50,7 +53,7 @@ export interface SpaceAPI {

   /* Returns a list of scheduled actions for a given entity */
   getEntityScheduledActions: (
-    entityType: EntityType,
+    entityType: ContentEntityType,
     entityId: string
   ) => Promise<ScheduledAction[]>
   /* Returns a list of scheduled actions for the currenst space & environment */
  getAllScheduledActions: () => Promise<ScheduledAction[]>

  signRequest: (request: CanonicalRequest) => Promise<Record<string, string>>

  createTag: (id: string, name: string, visibility?: TagVisibility) => Promise<Tag>
  readTags: (skip: number, limit: number) => Promise<CollectionResponse<Tag>>
  updateTag: (id: string, name: string, version: number) => Promise<Tag>
  deleteTag: (id: string, version: number) => Promise<boolean>
}
```

**Comment by andipaetzold** [comment]
Why do you call the files `*.types.ts`. It should be fine to remove the `.types.` part as they are located in `lib/types` and it's therefore clear that they are about types.

**Comment by shikaan** [comment]
> Why do you call the files `*.types.ts`. It should be fine to remove the `.types.` part as they are located in `lib/types` and it's therefore clear that they are about types.

@andipaetzold It was mainly to make them fuzzy-searchable with a unique name. I am not super opinionated though, given the size of this codebase

**Pull request merged**
